#  The Numpy.random package


<img src="https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png" />



***


### Explain the overall purpose of the package - numpy.random()
***

The **random** is a module present in the NumPy library. This module contains the functions which are used for generating random numbers, module contains:
  * simple random data,
  * permutations,
  * distributions,
  * random generator.

**Random number** does **NOT** mean a different number every time. **Random** means something that can not be predicted logically.

*Below are links with full documentation about the module.*  

- numpy.random() documentation [click here](https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#module-numpy.random)

- This is documentation for an old release of NumPy (version 1.16) [click here](https://numpy.org/doc/1.16/reference/routines.random.html)

- Numpy v1.21 Overview [click here](https://numpy.org/doc/stable/)


***

#### Modules
To dig deeper into the module, we will need do to few imports of libraries that gonna be used in the below description:


In [3]:
# import numpy as np
import numpy as np

#import plotting
import matplotlib.pyplot as plt


### Simple Random Data
***

The numpy random has ability to generate random list of data. Functions included in simple random data return array of data with random values in specified scope and shape. 
Functions included here are:
- rand
- randn
- randint
- random_integers
- random_sample
- random
- ranf
- sample
- choice
- bytes.



We will look into ***rand*** function to see how it works.

rand function syntax:
```
     numpy.random.rand(d0, d1, ..., dn)
     
``` 
d - for dimensions

If no argument is given a single Python float is returned.
***

In [4]:
# use rand to genarate numpy array with random values from 0 up to, but not including  1 in specify shape.
rgn = np.random.rand()
print(rgn)

0.44663207030150864


Function rand used without parameters will generate one random number in the scope 0-1. Each time when we will use the function it will generate a different number. Lets try it few times:

In [5]:
print("first number is: ", np.random.rand())

first number is:  0.9851629179985266


In [6]:
print("second number is: ", np.random.rand())

second number is:  0.41958043160868164


In [7]:
print("third number is: ", np.random.rand())

third number is:  0.6705723407009128


By using only one parameter _(8)_ we will get 1D Array filled with random values.

In [8]:
rgn = np.random.rand(8)
print(rgn)

[0.14258597 0.68419243 0.69730558 0.29644666 0.54495927 0.93943113
 0.65433683 0.0595687 ]


By using two parameters _(5,3)_ we will get the array with 5 columns and 3 rows. 

In [9]:
rgn = np.random.rand(5,3)
print(rgn)

[[0.382044   0.18044041 0.07964592]
 [0.65533472 0.65675037 0.8343204 ]
 [0.69506093 0.8548974  0.7279628 ]
 [0.06920066 0.64740959 0.21392744]
 [0.73671002 0.99526013 0.56728576]]


To change the range we can multiply the function by the largest number that we want to produce. 

In [15]:
# multiply function by 10 
rgn = 10 * np.random.rand(5,3)
print(rgn)

[[3.17608061 4.93313814 7.44441724]
 [0.65177193 2.92409987 7.47544842]
 [2.70363092 7.80985139 6.22657916]
 [1.52141107 3.27700009 6.07459235]
 [4.24487578 2.33243825 0.63898376]]


Now the result contains random numbers from 0 up to 10.

### Permutation
***

### Distribution
***

### Seeds
***