#  The Numpy.random package


<img src="https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png" />



***


### Explain the overall purpose of the package - numpy.random()
***

The **random** is a module present in the NumPy library. This module contains the functions which are used for generating random numbers, module contains:
  * simple random data,
  * permutations,
  * distributions,
  * random generator.

**Random number** does **NOT** mean a different number every time. **Random** means something that can not be predicted logically.

*Below are links with full documentation about the module.*  

- numpy.random() documentation [click here](https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#module-numpy.random)

- This is documentation for an old release of NumPy (version 1.16) [click here](https://numpy.org/doc/1.16/reference/routines.random.html)

- Numpy v1.21 Overview [click here](https://numpy.org/doc/stable/)


***

#### Modules
To dig deeper into the module, we will need do to few imports of libraries that gonna be used in the below description:


In [2]:
# import numpy as np
import numpy as np

#import plotting
import matplotlib.pyplot as plt


***
***

### Simple Random Data
***

The numpy random has ability to generate random list of data. Functions included in simple random data return array of data with random values in specified scope and shape. 
Functions included here are:
- rand
- randn
- randint
- random_integers
- random_sample
- random
- ranf
- sample
- choice
- bytes.



We will look into ***rand*** function to see how it works.

***rand*** function syntax:
```
     numpy.random.rand(d0, d1, ..., dn)
     
``` 
d - for dimensions

If no argument is given a single Python float is returned.
***

In [4]:
# use rand without an argument.
rgn = np.random.rand()
print(rgn)

0.5666126046891469


Function rand used without parameters will generate one random number in the scope 0-1. Each time when we will use the function it will generate a different number. Lets try it few times:

In [5]:
print("first number is: ", np.random.rand())

first number is:  0.9851629179985266


In [6]:
print("second number is: ", np.random.rand())

second number is:  0.41958043160868164


In [7]:
print("third number is: ", np.random.rand())

third number is:  0.6705723407009128


By using only one parameter _(8)_ we will get 1D Array filled with random values.

In [8]:
# use rand with one argument.
rgn = np.random.rand(8)
print(rgn)

[0.14258597 0.68419243 0.69730558 0.29644666 0.54495927 0.93943113
 0.65433683 0.0595687 ]


By using two parameters _(5,3)_ we will get the array with 5 columns and 3 rows. 

In [9]:
# use rand with two parameters.
rgn = np.random.rand(5,3)
print(rgn)

[[0.382044   0.18044041 0.07964592]
 [0.65533472 0.65675037 0.8343204 ]
 [0.69506093 0.8548974  0.7279628 ]
 [0.06920066 0.64740959 0.21392744]
 [0.73671002 0.99526013 0.56728576]]


To change the range we can multiply the function by the largest number that we want to produce. 

In [23]:
# multiply function by 10 
rgn = 10 * np.random.rand(5,3)
print(rgn)

[[8.32366026 6.64252489 5.00940155]
 [0.24978817 0.28213953 7.59596048]
 [8.55222339 6.98480322 9.51684554]
 [3.93128985 6.74235349 0.79807133]
 [7.50635378 1.9299808  6.87640683]]


Now the result contains random numbers from 0 up to 10.
***
***

### Permutation
***


The numpy.random library has two function that performs permutations or shuffling data:
* shuffle
* permutation.


Let's look into permutation function. 

***NOTE*** 
The key differences between the permutation() and shuffle() functions are that if passed an array, the permutation() function returns a shuffled copy of the original array. In contrast, the shuffle() function shuffles the original array.

Two main purposes of ***permutation*** function:
- to get a randomly permuted copy of a sequence
- to get a randomly permuted range in Python.

***permutation*** function syntax:

```
    np.random.permutation(x)
```
If no argument is given we will get TypeError:
```
TypeError: permutation() takes exactly one argument (0 given)
```


As one argument is needed for function to work, we can differ two types of arguments that can be passed to function:
* an integer - 
* an array - 

With an integer argument , function will give us a randomly permuted sequence of numbers with the given length.

In [22]:
# passing as an argument, an integer 
arg_int_2 = np.random.permutation(2)
print("with argument 2 --> ",arg_int)

arg_int_20 = np.random.permutation(20)
print("with argument 20 --> ", arg_int_20)

with argument 2 -->  [0 1]
with argument 20 -->  [17  9 16  3  2  8  7  1 18 12 14 11  6 10  0 19  4 13 15  5]


***NOTE** 

Each running of the code will generate differently shuffle sequence. Try

With an array argument function will return a shuffled copy of the original array.

In [26]:
num_arr = [1,2,3,4,5,6,7,8,9]

print("original array ", num_arr)
print("shuffled array", np.random.permutation(num_arr))
print("original array after permutation", num_arr)


original array  [1, 2, 3, 4, 5, 6, 7, 8, 9]
shuffled array [4 3 7 5 9 2 8 1 6]
original array after permutation [1, 2, 3, 4, 5, 6, 7, 8, 9]


***
***

### Distribution
***

Distributions draw samples , many functions, we will describe few types of drawing samples. 

Description of distribution
 types
 
 - numpy.random.uniform
 - numpy.random.normal
 - numpy.random.chisquare
 - numpy.random.gamma
 - numpy.random.
 five choosen 
 
 

***

### Seeds
***

references:
***
***simple random data:***
- https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html
- https://www.w3schools.com/python/numpy/numpy_random.asp
- https://www.geeksforgeeks.org/random-sampling-in-numpy-random-function/
- https://numpy.org/doc/1.16/reference/routines.random.html
- https://numpy.org/doc/1.16/reference/generated/numpy.random.rand.html#numpy.random.rand
- https://www.geeksforgeeks.org/numpy-random-rand-python/

***
***permutations:***
- https://www.w3schools.com/python/numpy/numpy_random_permutation.asp
- https://numpy.org/doc/1.16/reference/generated/numpy.random.permutation.html#numpy.random.permutation
- https://www.codegrepper.com/code-examples/python/numpy+random+permutation
- https://codingstreets.com/introduction-to-python-numpy-random-permutations/
- https://www.delftstack.com/howto/numpy/python-numpy-random-permutation/
- https://www.geeksforgeeks.org/numpy-random-permutation-in-python/ 
- https://numpy.org/doc/stable/reference/random/generated/numpy.random.permutation.html



***
***distributions:***



***
***random generator:***


***