#  The Numpy.random package


<img src="https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png" />



***


### Explain the overall purpose of the package - numpy.random()
***

The **random** is a module present in the NumPy library. This module contains the functions which are used for generating random numbers, module contains:
  * simple random data,
  * permutations,
  * distributions,
  * random generator.


##### Note

**Random number** does **NOT** mean a different number every time. **Random** means something that can not be predicted logically.
Pseudo-random numbers are computer generated numbers that appear random, but are actually predetermined.

*Below are links with full documentation about the module.*  

- numpy.random() documentation [click here](https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#module-numpy.random)

- This is documentation for an old release of NumPy (version 1.16) [click here](https://numpy.org/doc/1.16/reference/routines.random.html)

- Numpy v1.21 Overview [click here](https://numpy.org/doc/stable/)


***

#### Modules
To dig deeper into the module, we will need do to few imports of libraries that gonna be used in the below description:


In [1]:
# import numpy as np
import numpy as np

#import plotting
import matplotlib.pyplot as plt


***
***

### Simple Random Data
***

The numpy random has ability to generate random list of data. Functions included in ***simple random data*** return array of data with random values in specified scope and shape. 
Functions included here are:
- rand
- randn
- randint
- random_integers
- random_sample
- random
- ranf
- sample
- choice
- bytes.



We will look into ***rand*** function to see how it works.

***rand*** function syntax:
```
     numpy.random.rand(d0, d1, ..., dn)
     
``` 
d - for dimensions

If no argument is given a single Python float is returned.
***

In [2]:
# use rand without an argument.
rgn = np.random.rand()
print(rgn)

0.2598499210242282


Function rand used without parameters will generate one random number in the scope 0-1. Each time when we will use the function it will generate a different number. Lets try it few times:

In [3]:
print("first number is: ", np.random.rand())

first number is:  0.5808397688364748


In [4]:
print("second number is: ", np.random.rand())

second number is:  0.54755735203937


In [5]:
print("third number is: ", np.random.rand())

third number is:  0.2982120050776269


By using only one parameter _(8)_ we will get 1D Array filled with random values.

In [6]:
# use rand with one argument.
rgn = np.random.rand(8)
print(rgn)

[0.55134425 0.54420685 0.50285726 0.71257399 0.48785596 0.68930906
 0.43376929 0.26573886]


By using two parameters _(5,3)_ we will get the array with 5 columns and 3 rows. 

In [7]:
# use rand with two parameters.
rgn = np.random.rand(5,3)
print(rgn)

[[0.79297455 0.177207   0.6722317 ]
 [0.17542855 0.043214   0.54566486]
 [0.72128988 0.45090695 0.51219981]
 [0.56705023 0.66684776 0.27191196]
 [0.95686511 0.84986389 0.36304392]]


To change the range we can multiply the function by the largest number that we want to produce. 

In [8]:
# multiply function by 10 
rgn = 10 * np.random.rand(5,3)
print(rgn)

[[1.86603605 2.42923857 8.72649211]
 [6.06869041 8.11214081 8.14770549]
 [7.00002613 5.2757348  8.4826076 ]
 [2.65131441 5.49485131 3.99914967]
 [2.43710512 2.41302265 3.09174627]]


Now the result contains random numbers from 0 up to 10.
***
***

### Permutation
***


The numpy.random library has two function that performs permutations or shuffling data:
* shuffle
* permutation.


Let's look into permutation function. 

##### Note
The key differences between the permutation() and shuffle() functions are that if passed an array, the permutation() function returns a shuffled copy of the original array. In contrast, the shuffle() function shuffles the original array.

Two main purposes of ***permutation*** function:
- to get a randomly permuted copy of a sequence
- to get a randomly permuted range in Python.

***permutation*** function syntax:

```
    np.random.permutation(x)
```
If no argument is given we will get TypeError:
```
TypeError: permutation() takes exactly one argument (0 given)
```


As one argument is needed for function to work, we can differ two types of arguments that can be passed to function:
* an integer - 
* an array - 

With an integer argument , function will give us a randomly permuted sequence of numbers with the given length.

In [9]:
# passing as an argument, an integer 
arg_int_2 = np.random.permutation(2)
print("with argument 2 --> ",arg_int_2)

arg_int_20 = np.random.permutation(20)
print("with argument 20 --> ", arg_int_20)

with argument 2 -->  [0 1]
with argument 20 -->  [ 0  7 11  1 16 17  8 13  9  5  2  4 18 10 19 14  6 12  3 15]


##### Note

Each running of the code will generate differently shuffle sequence.

With an array argument function will return a shuffled copy of the original array.

In [10]:
# passing an array/list as an argument
num_arr = [1,2,3,4,5,6,7,8,9]

print("original array ", num_arr)
print("shuffled array", np.random.permutation(num_arr))
print("original array after permutation", num_arr)


original array  [1, 2, 3, 4, 5, 6, 7, 8, 9]
shuffled array [6 8 9 3 2 1 7 4 5]
original array after permutation [1, 2, 3, 4, 5, 6, 7, 8, 9]


***
***

### Random generator
***

In the numpy.random module we have also access to the random generator. Here we can find 4 functions:
- RandomState
- seed
- get_state
- set_state.


Let's look into ***seed*** function

```
    np.random.seed(seed=None)
```

Here we have only one parameter that we can choose which is ***seed*** value that will be used to "seed" the pseudo-random number generator.

By definition np.random.seed() is simply function that sets the random seed of the NumPy pseud-random number generator. It provides an essential input that enables NumPy to generate pseudo-random numbers for random processes.

***Other words*** if you run the algorithm with the same input , it will produce the same output. So you can use "seed" to create and thn re-create the exact same set of pseudo-random numbers.

***Note*** 
Importantly, numpy.random.seed doesn’t exactly work all on its own, function works in conjunction with other functions from NumPy.
Specifically, numpy.random.seed works with other function from the numpy.random namespace.

Let's see above rules in practice:

In [11]:
# we will use familiar method from above - numpy.random.rand()
rgn = np.random.rand(5,3)
print(rgn)

[[0.71583883 0.90085598 0.16977482]
 [0.02052513 0.22344645 0.21907754]
 [0.18776307 0.18094429 0.32633145]
 [0.7054325  0.45459081 0.64653825]
 [0.0396531  0.14017249 0.25135253]]


Rand function will produce randomly generated array of numbers between 0-1. When we will run the same code again, we will get different array of numbers.

Now lets do the same but with using ***seed***...

In [12]:
# using seed with rand function.
np.random.seed(0)
rgn = np.random.rand(5,3)
print(rgn)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]


And we see that code genreated array with random numbers, but here if we run the same code again, the number will stay ***the same***. Let's try ....

In [13]:
# Run the same code again.
np.random.seed(0)
rgn = np.random.rand(5,3)
print(rgn)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]


Result is exacly the same like above.

***Note*** 
Here we use just one parameter to seed - 0.
Let's see what will happen if we change it. And also we will change the function that we will see that example on. 
Let's generate some random integers.

Let's generate some random integers, to do that we gonna use ***randint*** function. 
    ```np.random.randint()
    ```

In [14]:
# why just simply generate random, let's play dice 
dices = np.random.randint(1,7, size=2)
print(dices)

[2 5]


Each run of above code will generate random generation of two integers 1-6 (in parameter is 7 but it's exclusive). 

In [15]:
# use seed method 
np.random.seed(0)
dices = np.random.randint(1,7, size=2)
print(dices)

[5 6]


Hard to belive for a word, so lets copy the code and see....

In [16]:
# another use of the same code, with the same seed
np.random.seed(0)
dices = np.random.randint(1,7, size=2)
print(dices)

[5 6]


And output is exacly the same.

What about different seed.

In [17]:
# let's change the seed to 10 
np.random.seed(10)
dices = np.random.randint(1,7, size=2)
print(dices)

[2 6]


Running above code again will give exacly the same output.

***Note***
If you give a pseudo-random number generator the same input, you'll get the same output.
And code that has well defined, repeatable outputs is good for testing. Also is good in case that code has to be shared and we want to keep exacly the same group for testing. 

***
***

### Distributions
***

In this part we will go throught functions that draw samples based on a specify distribution.
Whitin this category we will have many variations exists to produce many combinations of random data with varing distributions.
Since list of these functions is long, we will focus on few choosen:
 
 - numpy.random.normal
 - numpy.random.uniform
 - numpy.random.chisquare
 - numpy.random.gamma
 - numpy.random.


 
 

***

##### numpy.random.normal

First function that we gonna look into is ***numpy.random.normal***:

```
    numpy.random.normal(loc=0.0, scale=1.0, size=None)
    
```
***parameters***:
- ***loc*** - this parameter controls the mean of the function. It defaults to 0, so if you dont use this parameter to specify the mean of the distribution, the mean will be at 0. 
- ***scale*** - controls the standard deviation of the normal distribution. By default it's set to 1. It must not be a negative value.
- ***size*** - this one controls the size and shape of the output. If you provide a single integer, x, np.random.normal will provide x random normal values in a 1-dimensional NumPy array. For example, if you specify size = (2, 3), np.random.normal will produce a numpy array with 2 rows and 3 columns. It will be filled with numbers drawn from a random normal distribution.

***Note***
All of those parameters are optional, so by not choosing them they will be set to default.
- loc - default is 0
- scale - default is 1
- size - default is 1.



This function draw random samples from a normal (Gaussian) distribution. 
Normally distributed data is shaped sort of like a bell, so it’s often called the “bell curve.”


***Firstly*** let's create *np.random.normal() function with one parameter and we will start from the ***loc*** parameter.

In [19]:
# function with only loc as a given parameter.
loc_parameter = np.random.normal(loc=5)
print(loc_parameter)

4.86455150844399


***loc*** means the mean value of the random values chose from the function, other words is where the peak of the bell exists. So the output will be one number close to the mean that we choose, in this case is 5. Each run of code will give us different result.


***Secondly*** let's create np.random.normal() function with one parameter choosen and this time let's go with ***scale***.

In [30]:
# function with only scale as a given parameter.
scale_parameter = np.random.normal(scale=5.0)
print(scale_parameter)

7.452868186244963


***scale*** means the standard deviation of the values choosen from the function. Also each run of code will give us a different result.

***Thirdly*** let's create np.random.normal() with ***size*** as a choosen parameter.

In [32]:
# function with only size as a given parameter.
size_parameter = np.random.normal(size=5)
print(size_parameter)

[-0.35030121 -0.9896496  -0.63425417  1.89876222  1.99652279]


***size*** means the number of values in the array, so here we have array with five elements. As with other two cases, each run of code will generate different set of numbers, but still will be five of them.

***
***
            ``` References: ```
***
***simple random data:***
- https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html
- https://www.w3schools.com/python/numpy/numpy_random.asp
- https://www.geeksforgeeks.org/random-sampling-in-numpy-random-function/
- https://numpy.org/doc/1.16/reference/routines.random.html
- https://numpy.org/doc/1.16/reference/generated/numpy.random.rand.html#numpy.random.rand
- https://www.geeksforgeeks.org/numpy-random-rand-python/

***
***permutations:***
- https://www.w3schools.com/python/numpy/numpy_random_permutation.asp
- https://numpy.org/doc/1.16/reference/generated/numpy.random.permutation.html#numpy.random.permutation
- https://www.codegrepper.com/code-examples/python/numpy+random+permutation
- https://codingstreets.com/introduction-to-python-numpy-random-permutations/
- https://www.delftstack.com/howto/numpy/python-numpy-random-permutation/
- https://www.geeksforgeeks.org/numpy-random-permutation-in-python/ 
- https://numpy.org/doc/stable/reference/random/generated/numpy.random.permutation.html

***
***random generator/seeds:***
- https://likegeeks.com/numpy-random-seed/
- https://coderedirect.com/questions/113090/what-does-numpy-random-seed0-do
- https://www.py4u.net/discuss/15203
- https://www.sharpsightlabs.com/blog/numpy-random-seed/
- https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.seed.html#numpy.random.seed
- https://stackoverflow.com/questions/21494489/what-does-numpy-random-seed0-do
- https://www.youtube.com/watch?v=y4t8MuKqKt8
- https://www.youtube.com/watch?v=gVlLnQU9pPc

***
***distributions:***

- normal distrubution:
    * https://www.geeksforgeeks.org/rand-vs-normal-numpy-random-python/
    * https://www.pythonpool.com/numpy-random-normal/
    * https://www.w3schools.com/python/numpy/numpy_random_normal.asp
    * https://numpy.org/doc/stable/reference/random/generator.html
    * https://www.youtube.com/watch?v=uial-2girHQ
    * https://www.youtube.com/watch?v=ToiYdi_cWw0
    * https://www.youtube.com/watch?v=ig_FutNrcO8



***
***