#  The Numpy.random package


<img src="https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png" />



***


### Explain the overall purpose of the package - numpy.random()
***

The **random** is a module present in the NumPy library. This module contains the functions which are used for generating random numbers, module contains:
  * simple random data,
  * permutations,
  * distributions,
  * random generator.


##### Note

**Random number** does **NOT** mean a different number every time. **Random** means something that can not be predicted logically.
Pseudo-random numbers are computer generated numbers that appear random, but are actually predetermined.

*Below are links with full documentation about the module.*  

- numpy.random() documentation [click here](https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#module-numpy.random)

- This is documentation for an old release of NumPy (version 1.16) [click here](https://numpy.org/doc/1.16/reference/routines.random.html)

- Numpy v1.21 Overview [click here](https://numpy.org/doc/stable/)


***

#### Modules
To dig deeper into the module, we will need do to few imports of libraries that gonna be used in the below description:


In [1]:
# import numpy as np
import numpy as np

#import plotting
import matplotlib.pyplot as plt


***
***

### Simple Random Data
***

The numpy random has ability to generate random list of data. Functions included in ***simple random data*** return array of data with random values in specified scope and shape. 
Functions included here are:
- rand
- randn
- randint
- random_integers
- random_sample
- random
- ranf
- sample
- choice
- bytes.



We will look into ***rand*** function to see how it works.

***rand*** function syntax:
```
     numpy.random.rand(d0, d1, ..., dn)
     
``` 
d - for dimensions

If no argument is given a single Python float is returned.
***

In [2]:
# use rand without an argument.
rgn = np.random.rand()
print(rgn)

0.08812872604168154


Function rand used without parameters will generate one random number in the scope 0-1. Each time when we will use the function it will generate a different number. Lets try it few times:

In [3]:
print("first number is: ", np.random.rand())

first number is:  0.5604324472452762


In [4]:
print("second number is: ", np.random.rand())

second number is:  0.9083672768196669


In [5]:
print("third number is: ", np.random.rand())

third number is:  0.7389353498192021


By using only one parameter _(8)_ we will get 1D Array filled with random values.

In [6]:
# use rand with one argument.
rgn = np.random.rand(8)
print(rgn)

[0.10215069 0.64814163 0.54462932 0.0423895  0.47496681 0.16181471
 0.75756678 0.55004914]


By using two parameters _(5,3)_ we will get the array with 5 columns and 3 rows. 

In [7]:
# use rand with two parameters.
rgn = np.random.rand(5,3)
print(rgn)

[[0.88110314 0.91014077 0.19193398]
 [0.94809794 0.86233299 0.35760372]
 [0.50642976 0.57141545 0.8887227 ]
 [0.3459395  0.219369   0.7955649 ]
 [0.62838354 0.77789727 0.73155027]]


To change the range we can multiply the function by the largest number that we want to produce. 

In [8]:
# multiply function by 10 
rgn = 10 * np.random.rand(5,3)
print(rgn)

[[7.5690858  3.80782687 0.18615312]
 [3.31636674 8.51302348 7.2381311 ]
 [7.59650948 0.72893752 9.17566342]
 [8.67827019 7.96371375 2.95411474]
 [0.77149266 1.98719965 8.11908104]]


Now the result contains random numbers from 0 up to 10.
***
***

### Permutation
***


The numpy.random library has two function that performs permutations or shuffling data:
* shuffle
* permutation.


Let's look into permutation function. 

##### Note
The key differences between the permutation() and shuffle() functions are that if passed an array, the permutation() function returns a shuffled copy of the original array. In contrast, the shuffle() function shuffles the original array.

Two main purposes of ***permutation*** function:
- to get a randomly permuted copy of a sequence
- to get a randomly permuted range in Python.

***permutation*** function syntax:

```
    np.random.permutation(x)
```
If no argument is given we will get TypeError:
```
TypeError: permutation() takes exactly one argument (0 given)
```


As one argument is needed for function to work, we can differ two types of arguments that can be passed to function:
* an integer - 
* an array - 

With an integer argument , function will give us a randomly permuted sequence of numbers with the given length.

In [16]:
# passing as an argument, an integer 
arg_int_2 = np.random.permutation(2)
print("with argument 2 --> ",arg_int_2)

arg_int_20 = np.random.permutation(20)
print("with argument 20 --> ", arg_int_20)

with argument 2 -->  [0 1]
with argument 20 -->  [ 2  3 14 17  5 11  0 13 18 19 16  1 10 12 15  8  6  4  9  7]


##### Note

Each running of the code will generate differently shuffle sequence.

With an array argument function will return a shuffled copy of the original array.

In [ ]:
# passing an array/list as an argument
num_arr = [1,2,3,4,5,6,7,8,9]

print("original array ", num_arr)
print("shuffled array", np.random.permutation(num_arr))
print("original array after permutation", num_arr)


***
***

### Distribution
***

Distributions draw samples , many functions, we will describe few types of drawing samples. 

Description of distribution
 types
 
 - numpy.random.uniform
 - numpy.random.normal
 - numpy.random.chisquare
 - numpy.random.gamma
 - numpy.random.
 five choosen 
 
 

***

First function that we gonna look into is ***numpy.random.normal***:

```
    numpy.random.normal(loc=0.0, scale=1.0, size=None)
    
```
***parameters***:
- ***loc*** - this parameter controls the mean of the function. It defaults to 0, so if you dont use this parameter to specify the mean of the distribution, the mean will be at 0.
- ***scale*** - controls the standard deviation of the normal distribution. By default it's set to 1.
- ***size*** - this one controls the size and shape of the output. If you provide a single integer, x, np.random.normal will provide x random normal values in a 1-dimensional NumPy array. For example, if you specify size = (2, 3), np.random.normal will produce a numpy array with 2 rows and 3 columns. It will be filled with numbers drawn from a random normal distribution.

This function draw random samples from a normal (Gaussian) distribution. 



Normally distributed data is shaped sort of like a bell, so it’s often called the “bell curve.”


***examples** 
- single number from the normal distribution
- draw 5 numbers 
- create a 2-d numpy array 
- generate normally distributed values with specific mean
- same but with specific standard deviation
- how to use loc and scale


maybe starts from description of seeds .... 

### Random generator
***

In the numpy.random module we have also access to the random generator. Here we can find 4 functions:
- RandomState
- seed
- get_state
- set_state.

The “random” numbers generated by NumPy are not exactly random. They are pseudo-random … they approximate random numbers, but are 100% determined by the input and the pseudo-random number algorithm.

The np.random.seed function provides an input for the pseudo-random number generator in Python.

In [18]:
# rolling dice random 
dices = np.random.randint(1,7, size=2)
print(dices)

[1 4]


In [19]:
# use seed method 
np.random.seed(0)
dices = np.random.randint(1,7, size=2)
print(dices)

[5 6]


In [21]:
dices = np.random.randint(1,7, size=2)
print(dices)

[4 4]


references:
***
***simple random data:***
- https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html
- https://www.w3schools.com/python/numpy/numpy_random.asp
- https://www.geeksforgeeks.org/random-sampling-in-numpy-random-function/
- https://numpy.org/doc/1.16/reference/routines.random.html
- https://numpy.org/doc/1.16/reference/generated/numpy.random.rand.html#numpy.random.rand
- https://www.geeksforgeeks.org/numpy-random-rand-python/

***
***permutations:***
- https://www.w3schools.com/python/numpy/numpy_random_permutation.asp
- https://numpy.org/doc/1.16/reference/generated/numpy.random.permutation.html#numpy.random.permutation
- https://www.codegrepper.com/code-examples/python/numpy+random+permutation
- https://codingstreets.com/introduction-to-python-numpy-random-permutations/
- https://www.delftstack.com/howto/numpy/python-numpy-random-permutation/
- https://www.geeksforgeeks.org/numpy-random-permutation-in-python/ 
- https://numpy.org/doc/stable/reference/random/generated/numpy.random.permutation.html



***
***distributions:***



***
***random generator/seeds:***


***